### ISSUE TITLE
Option to automatically add `target="_blank"` to external links

### ISSUE THREAD

**Issue by ed-ponce** [JKC-Codes/eleventy-plugin-automatic-noopener#1]
It could be beyond the scope of this project, but it could be handy to add an option to add `target="_blank"` to external links, site-wide.

[`markdown-it-link-attributes`](https://www.npmjs.com/package/markdown-it-link-attributes) has a similar implementation of this but it only has effect on code transpiled by `markdown-it`.

**Comment by JKC-Codes** [comment]
This is out of scope I'm afraid. The studies I've seen have mostly considered links opening in a new window to lead to a poor user experience so it's not something I'd want to encourage by adding it to this plugin.
