### ISSUE TITLE
Is it support markdown file?

### ISSUE THREAD

**Issue by bingqichen** [JKC-Codes/eleventy-plugin-automatic-noopener#2]
Is it support `.md` file? I try to config it but there is no effective.

**Comment by JKC-Codes** [comment]
Yes, Markdown is supported. The plugin looks at the compiled HTML so works with all template languages.

What link is not working?

**Comment by bingqichen** [comment]
@JKC-Codes  Thank you for your reply. And unfortunately, the plugin is not working, you can get the code from [demo](https://stackblitz.com/edit/js-kpektj?file=package.json).

**Comment by bingqichen** [comment]
Maybe I know the reason why it doesn't work, the plugin is only effective the external link, but the markdown file not add attribute `target='_blank'`, I have resolved it.
But the plugin have another problem, when i add `rel="noopener noreferrer"` in a link, the plugin will transform to `rel="noopener noreferrer noopener"`, can you resolved it in next version?

**Comment by JKC-Codes** [comment]
> Maybe I know the reason why it doesn't work, the plugin is only effective the external link, but the markdown file not add attribute `target='_blank'`, I have resolved it.

Yes, the link is safe without `target='_blank'` so `noopener` is not added.

> But the plugin have another problem, when i add `rel="noopener noreferrer"` in a link, the plugin will transform to `rel="noopener noreferrer noopener"`, can you resolved it in next version?

This should be fixed in 2.0.1 Thank you!
